//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekENotionsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class photo
    {
        public int id { get; set; }
        public string caption_html { get; set; }
        public string copyright_holder { get; set; }
        public string caption { get; set; }
        public string medium2_url { get; set; }
        public string medium_url { get; set; }
        public string small2_url { get; set; }
        public string small_url { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string square_url { get; set; }
        public string thumbnail_url { get; set; }
        public Nullable<double> x_offset { get; set; }
        public Nullable<double> y_offset { get; set; }
    }
}
