//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekENotionsWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TekENotionsEntities : DbContext
    {
        public TekENotionsEntities()
            : base("name=TekENotionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserSetting> UserSettings { get; set; }
        public virtual DbSet<needle_types> needle_types { get; set; }
        public virtual DbSet<needle_sizes> needle_sizes { get; set; }
        public virtual DbSet<pattern> patterns { get; set; }
        public virtual DbSet<pattern_author> pattern_author { get; set; }
        public virtual DbSet<photo> photos { get; set; }
        public virtual DbSet<yarn_weight> yarn_weight { get; set; }
        public virtual DbSet<yarn> yarns { get; set; }
        public virtual DbSet<pattern_needle_size> pattern_needle_size { get; set; }
        public virtual DbSet<tekENotionsNeedleSize> tekENotionsNeedleSizes { get; set; }
        public virtual DbSet<CircularNeedleSize> CircularNeedleSizes { get; set; }
        public virtual DbSet<UserNeedleInventory> UserNeedleInventories { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<UserModel> UserModels { get; set; }
        public virtual DbSet<NeedleDescriptionLookup> NeedleDescriptionLookups { get; set; }
    }
}
