//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekENotionsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tekENotionsNeedleSize
    {
        public int id { get; set; }
        public string description { get; set; }
        public string needleType { get; set; }
        public Nullable<int> showOrder { get; set; }
    }
}
