//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekENotionsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNeedleInventory
    {
        public int id { get; set; }
        public string userId { get; set; }
        public string needlelength { get; set; }
        public string needlesize { get; set; }
        public string needletype { get; set; }
        public Nullable<int> howmany { get; set; }
        public Nullable<int> howmanyinuse { get; set; }
        public Nullable<int> ravelryId { get; set; }
        public string ravelryName { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string userdescription { get; set; }
        public string systemName { get; set; }
    }
}
