//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekENotionsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yarn_weight
    {
        public int id { get; set; }
        public string ply { get; set; }
        public string crochet_gauge { get; set; }
        public string wpi { get; set; }
        public string name { get; set; }
        public string knit_gauge { get; set; }
    }
}
