//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekENotionsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yarn
    {
        public int id { get; set; }
        public string yarn_company_name { get; set; }
        public Nullable<int> rating_total { get; set; }
        public Nullable<decimal> max_gauge { get; set; }
        public Nullable<int> first_photo_id { get; set; }
        public string permalink { get; set; }
        public Nullable<decimal> min_gauge { get; set; }
        public Nullable<int> grams { get; set; }
        public Nullable<bool> discontinued { get; set; }
        public Nullable<decimal> gauge_divisor { get; set; }
        public string texture { get; set; }
        public string name { get; set; }
        public Nullable<decimal> rating_average { get; set; }
        public Nullable<bool> machine_washable { get; set; }
        public Nullable<int> yarn_weight_id { get; set; }
        public Nullable<int> yardage { get; set; }
    }
}
